---
- name: Create partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
    part_start: 0%
    part_end: 800MiB
    flags: [ lvm ]

- name: Create VG
  lvg:
    vg: vg_database
    pvs: /dev/sdb1

- name: Create LV
  lvol:
    lv: lv_mysql
    vg: vg_database
    size: 512M

- name: Create Filesystem
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql

- name: Create mountpoint
  file:
    path: /mnt/mysql_backups
    state: directory

- name: Mount Filesystem
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted
  

