---
- name: Task 15 - Work with Ansible Facts
  hosts: database
  become: True
  gather_facts: False
  tasks:

    - name: Create custom fact
      blockinfile:
        path: /etc/ansible/facts.d/custom.fact
        block: |
          [sample_exam]
          server_role=mysql
        create: True

    - name: Run setup module
      setup:

    - name: Print custom fact
      debug:
        msg: Server role is {{ ansible_local['custom']['sample_exam']['server_role'] }}

    - name: TEST
      debug:
        var: ansible_facts['ansible_local']['custom']['sample_exam']['server_role']
...
