---
- name: MOTD
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Template MOTD
      template:
        src: templates/motd_alt.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
