---
- name: Task12 - SELinux System Role
  hosts: webservers
  become: True
  become_user: root
  become_method: sudo
  vars:
    selinux_policy: targeted
    selinux_state: enforcing
    selinux_booleans:
      - name: 'httpd_can_network_connect'
        state: on
        persistent: yes
  roles:
    - role: rhel-system-roles.selinux
