---
- name: Task 18 - Create and Use Templates
  hosts: all
  become: yes

  tasks:
    - name: Template file
      template:
        src: templates/server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        mode: '0600'
        setype: net_conf_t
      when: inventory_hostname in groups['database']
