---
- name: Task 17 - Change default boot target to multi-user
  hosts: webservers
  become: yes
  gather_facts: no
  tasks:

    - name:  Change default boot target to multi-user
      file:
        src: /usr/lib/systemd/system/multi-user.target
        path: /etc/systemd/system/default.target
        state: link
...
